[package]
name = "rust_cp_tool"
version = "0.1.0"
edition = "2021"

[dependencies]

text_io = "0.1.12"

num = "0.4"

itertools = "0.14.0"

rand = "0.8"

assert_cmd = "2.0"

regex = "1.11.1"

cliclack = "0.3.5"


[[bin]]
name = "main"
path = "src/main.rs"
